#ifndef EVENTTYPE_H_
#define EVENTTYPE_H_

namespace nfe {
	enum EventType {
		ALL,
		EVENT_TEST,
		UNINITIALIZED,
		EVENT_WINDOW_CLOSE, EVENT_WINDOW_RESIZE, // Window events
		EVENT_KEY_PRESSED, EVENT_KEY_RELEASED, EVENT_KEY_TYPED, // Keyboard events
		EVENT_MOUSE_MOVED, EVENT_MOUSE_SCROLLED, EVENT_MOUSE_BUTTON_PRESSED, EVENT_MOUSE_BUTTON_RELEASED //Mouse events
	};
}
#endif